### ISSUE TITLE
19장 예제 03 (`ssia-ch19-ex3`) 테스트코드 수정 문의드립니다.

### ISSUE THREAD

**Issue by mklinkj** [wikibook/spring-security#2]
안녕하세요.

https://github.com/wikibook/spring-security/blob/1fdddba57ea9264150630dc1c1d00290148de4d7/ssia-ch19-ex3/src/test/java/com/laurentiuspilca/ssia/MainTests.java#L39-L48

인증된 유저 없이 /ciao 엔드 포인트에 접근해서 200응답을 받는지 확인하는 테스트여야하는데,

`@WithMockUser`가 붙어있습니다.

이 어노테이션은 제거 되야할 것 같습니다.

감사합니다. 좋은하루되세요. 👍

**Comment by wikibook** [comment]
@mklinkj 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 확인했는데, 따로 등록된 오탈자 내용은 아니지만 말씀해 주신 대로 문맥상 해당 `@WithMockUser` 애너테이션은 제거하는 것이 적절해 보입니다. 말씀해 주신 대로 예제 코드를 수정했습니다.

저희 책을 꼼꼼이 확인해 주셔서 감사합니다.
오늘도 편안한 하루 보내세요..!
고맙습니다.

**Comment by mklinkj** [comment]
반영 감사합니다. 좋은하루되세요. 👍
